spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/event-clean
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

