CREATE TABLE tb_events(
id BIGSERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
description TEXT,
identifier VARCHAR(255) NOT NULL UNIQUE,
start_date TIMESTAMP NOT NULL,
end_date TIMESTAMP NOT NULL,
address VARCHAR(255) NOT NULL,
organizer VARCHAR(100) NOT NULL,
capacity INTEGER NOT NULL,
event_type VARCHAR(50) NOT NULL
);