#1 Nome da ação
name: Build and deploy of EventCleanApi v1
#2 Gatilho da ação
on:
  push:
    branches: [main]
#3 Ação
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Project
        run: mvn clean install

      - name: Run all Tests
        run: mvn test

      - name: Build artifact
        run: mvn clean package

      - name: Store Artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp-jar
          path: target/*.jar

